### PR TITLE
Feat - implement chat ui

### PR DESCRIPTION
**Pull request by karnjj**

### CODE REVIEW

**Comment by karnjj** [comment]
image

**Comment by karnjj** [comment]
image

**Comment by karnjj** [comment]
image

**Comment by NonKhuna** [comment]
"send by [name]" should be the name of the sender of the message. In the picture, Why does the text "send by" appear to be an incremental number?

**Comment by karnjj** [comment]
> "send by [name]" should be the name of the sender of the message. In the picture, Why does the text "send by" appear to be an incremental number?

It is just mock data. In the code, I use the variable name `senderName` to pass the sender's name to each message.

**Pull request merged**
